### PR TITLE
Build without test cases if the test task is called previously

### PR DESCRIPTION
**Pull request by niveathika**
## Purpose
Fix the build task is not executing if the test task is called previously.

### CODE REVIEW

**Review by ThisaruGuruge — COMMENTED** [review]
Are we going to build with the tests first and then build without tests again now?

**Comment by niveathika** [comment]
Only if a build task is called including the disable/ groups param. 

Lets say we have another integration test module depending on module being build, in the above case, only the test will run and not the build. I was thinking may this is the issue for HTTTP windows failure.

**Comment by ThisaruGuruge** [comment]
> Only if a build task is called including the disable/ groups param.
> 
> Lets say we have another integration test module depending on module being build, in the above case, only the test will run and not the build. I was thinking may this is the issue for HTTTP windows failure.

This will affect the code coverage. Because when we re-build without the tests, the coverage file will not be generated. This might cause the coverage to incorrectly showing `0%` coverage. We had this issue earlier too. That's why we used this more complex approach to handle tests and the build.

**Comment by niveathika** [comment]
Closing this due to the above issue.

**Pull request closed without merging**
